/*CREATE TABLE CATEGORY (
  categoryId INT AUTO_INCREMENT PRIMARY KEY,
  categoryName VARCHAR(250) NOT NULL
);

CREATE TABLE ROLE (
  roleId INT AUTO_INCREMENT PRIMARY KEY,
  role VARCHAR(250) NOT NULL
);

CREATE TABLE USER (
  userId INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(250) NOT NULL,
  password VARCHAR(250) NOT NULL
);

CREATE TABLE CART (
  cartId INT AUTO_INCREMENT PRIMARY KEY,
  totalAmount DOUBLE NOT NULL,
  userId INT NOT NULL
);

CREATE TABLE USERROLE (
  userRoleId INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  role INT NOT NULL
);

CREATE TABLE PRODUCT (
  productId INT AUTO_INCREMENT PRIMARY KEY,
  productName VARCHAR(250) NOT NULL,
  price DOUBLE NOT NULL,
  categoryId INT NOT NULL,
  sellerId INT NOT NULL
);

CREATE TABLE CARTPRODUCT (
  cpId INT AUTO_INCREMENT PRIMARY KEY,
  cartId INT NOT NULL,
  productId INT NOT NULL,
  quantity INT NOT NULL
);*/